require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClicksController do

  # This should return the minimal set of attributes required to create a valid
  # Click. As you add validations to Click, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClicksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all clicks as @clicks" do
      click = Click.create! valid_attributes
      get :index, {}, valid_session
      assigns(:clicks).should eq([click])
    end
  end

  describe "GET show" do
    it "assigns the requested click as @click" do
      click = Click.create! valid_attributes
      get :show, {:id => click.to_param}, valid_session
      assigns(:click).should eq(click)
    end
  end

  describe "GET new" do
    it "assigns a new click as @click" do
      get :new, {}, valid_session
      assigns(:click).should be_a_new(Click)
    end
  end

  describe "GET edit" do
    it "assigns the requested click as @click" do
      click = Click.create! valid_attributes
      get :edit, {:id => click.to_param}, valid_session
      assigns(:click).should eq(click)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Click" do
        expect {
          post :create, {:click => valid_attributes}, valid_session
        }.to change(Click, :count).by(1)
      end

      it "assigns a newly created click as @click" do
        post :create, {:click => valid_attributes}, valid_session
        assigns(:click).should be_a(Click)
        assigns(:click).should be_persisted
      end

      it "redirects to the created click" do
        post :create, {:click => valid_attributes}, valid_session
        response.should redirect_to(Click.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved click as @click" do
        # Trigger the behavior that occurs when invalid params are submitted
        Click.any_instance.stub(:save).and_return(false)
        post :create, {:click => {}}, valid_session
        assigns(:click).should be_a_new(Click)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Click.any_instance.stub(:save).and_return(false)
        post :create, {:click => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested click" do
        click = Click.create! valid_attributes
        # Assuming there are no other clicks in the database, this
        # specifies that the Click created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Click.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => click.to_param, :click => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested click as @click" do
        click = Click.create! valid_attributes
        put :update, {:id => click.to_param, :click => valid_attributes}, valid_session
        assigns(:click).should eq(click)
      end

      it "redirects to the click" do
        click = Click.create! valid_attributes
        put :update, {:id => click.to_param, :click => valid_attributes}, valid_session
        response.should redirect_to(click)
      end
    end

    describe "with invalid params" do
      it "assigns the click as @click" do
        click = Click.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Click.any_instance.stub(:save).and_return(false)
        put :update, {:id => click.to_param, :click => {}}, valid_session
        assigns(:click).should eq(click)
      end

      it "re-renders the 'edit' template" do
        click = Click.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Click.any_instance.stub(:save).and_return(false)
        put :update, {:id => click.to_param, :click => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested click" do
      click = Click.create! valid_attributes
      expect {
        delete :destroy, {:id => click.to_param}, valid_session
      }.to change(Click, :count).by(-1)
    end

    it "redirects to the clicks list" do
      click = Click.create! valid_attributes
      delete :destroy, {:id => click.to_param}, valid_session
      response.should redirect_to(clicks_url)
    end
  end

end
